version: '3.4'

services:
  delivery-order-services:
    image: ${DOCKER_REGISTRY-}deliveryorderservices
    build:
      context: .
      dockerfile: delivery-order-services/Dockerfile
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/deliverydb
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka
    ports:
      - "5000:5000" # ajuste para a porta do seu serviço

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mongo_data:
